### ISSUE TITLE
一直显示正在加载请勿离开

### ISSUE THREAD

**Issue by hgtc13** [WeiWenda/effect-note#2]
![image](https://github.com/WeiWenda/effect-note/assets/59947313/ac078241-2115-4510-ac69-d77434e8d0a5)

**Comment by WeiWenda** [comment]
是有这个问题，可以先试试切换到Discovery、或者ctrl+r刷新、或者强退。我这边尽快出修复版本

**Comment by WeiWenda** [comment]
maybe fixed in https://github.com/WeiWenda/effect-note/commit/b25a076ee15ce52e44054bc136aafecca919792b
and released in https://github.com/WeiWenda/effect-note/releases/tag/v0.4.2

**Comment by hgtc13** [comment]
没有解决，重新安装也没用

**Comment by WeiWenda** [comment]
抱歉，v0.4.1引入了一个bug，导致不开启git同步的工作空间，会一直正在加载，fixed in https://github.com/WeiWenda/effect-note/commit/1e94114a56ae270d76fbd9a1f1d4109ebab7d19a, 0.4.2 window版下载链接已更新
