### ISSUE TITLE
Android 版本bug

### ISSUE THREAD

**Issue by harmonyharmo** [WeiWenda/effect-note#3]
感谢这个app！⭐⭐

Android 版本bug （一加测试）：

- 没法选中文本
- 按钮都挤在一起
- 没法打标签

**Comment by WeiWenda** [comment]
收到反馈，移动端选中文本和打标签的需求，我有空加一下。然后，按钮挤在一起可以截个图吗

**Comment by WeiWenda** [comment]
resolved in [1.0.2](https://github.com/WeiWenda/effect-note-mobile/releases/tag/v1.0.2)
