### ISSUE TITLE
Android 版没法打空格

### ISSUE THREAD

**Issue by harmonyharmo** [WeiWenda/effect-note#4]
1.0.2 版本

- 打空格会变成 `&nbsp;·`
- 希望按钮顺序反过来，我现在觉得最常用的按钮是在最后面。。
- 选文本的功能最好改进下，现在要松手才看到选了啥，最好选的时候就显示。

👍👍

**Comment by WeiWenda** [comment]
感谢反馈，下个版本会进行优化

**Comment by WeiWenda** [comment]
resolved in https://github.com/WeiWenda/effect-note-mobile/releases/tag/v1.0.3
